modLoader="javafml"
loaderVersion="[44,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Rexbas/Bouncing-Balls/issues"
logoFile="logo.png"
[[mods]]
modId="bouncingballs"
version="${file.jarVersion}"
displayName="Bouncing Balls"
updateJSONURL="https://raw.githubusercontent.com/Rexbas/Bouncing-Balls/update/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bouncing-balls"
authors="Rexbas"
description='''
Hop around the world with Bouncing Balls!
'''
[[dependencies.bouncingballs]]
    modId="bouncingballs_api"
    mandatory=true
    versionRange="[4.0,)"
    ordering="AFTER"
    side="BOTH"